# Generated by Django 6.0.3 on 2026-03-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(upload_to='excursions/')),
                ('description', models.TextField()),
                ('available_seats', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Sea', 'Sea'), ('Mountain', 'Mountain'), ('Cultural', 'Cultural'), ('Adventure', 'Adventure'), ('Family', 'Family'), ('Luxury', 'Luxury'), ('Romantic', 'Romantic')], max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursions', to='excursions.destination')),
                ('features', models.ManyToManyField(blank=True, to='excursions.feature')),
            ],
        ),
    ]
