# Generated by Django 6.0.3 on 2026-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='excursion',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
