# Generated by Django 6.0.3 on 2026-04-06 18:16

import excursions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_destination_slug_excursion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='available_seats',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[excursions.validators.validate_positive_price]),
        ),
    ]
