# Generated by Django 6.0.3 on 2026-03-28 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excursions', '0002_destination_slug_excursion_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.PositiveIntegerField()),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='excursions.excursion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='excursions.excursion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['excursion__title'],
                'constraints': [models.UniqueConstraint(fields=('user', 'excursion'), name='unique_user_excursion')],
            },
        ),
    ]
