# Generated by Django 6.0.3 on 2026-03-29 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('excursions', '0002_destination_slug_excursion_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'excursion'), name='unique_user_excursion_booking'),
        ),
    ]
